apiVersion: v1
kind: Service
metadata:
  name: service-pare-azul-junior
  namespace: viptech
spec:
  selector:
    app: pare-azul-junior
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort